logging:
  level:
    root: DEBUG
spring:
  application:
    name: ADDRESS_API
  main:
    allow-circular-references: true
  profiles.actives: dev
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.H2Dialect
       ddlAuto: update
  h2:
    console.enabled: true
bezkoder:
  app:
    jwtExpirationMs: 60000
    jwtSecret: ======================BezKoder=Spring===========================

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true