logging:
  level:
    root: DEBUG
spring:
  profiles.actives: dev
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.H2Dialect
       ddlAuto: update
  h2:
    console.enabled: true